---
en-US: 
  # The display name of this language file
  this_file_language: "English" 
  
  # Model Names
  user: 'User'
  users: 'Users'
  admin: 'Administrator' 
  designer: 'Designer'
  page: 'Page'
  pages: 'Pages'
  snippet: 'Snippet'
  snippets: 'Snippets'
  layout: 'Layout'
  layouts: 'Layouts'
  page_page: 'Page Part'
  
  # Shared Views
  slug: 'Slug'
  breadcrumb: 'Breadcrumb'
  description: 'Description'
  keywords: 'Keywords'
  modify: 'Modify' 
  more: 'More'
  hide: 'Hide' 
  body: 'Body'  
  name: 'Name'     
  filter: 'Filter'
  cancel: 'Cancel'
  or: 'or'
  remove: 'Remove'
  close: 'Close'
  
  # Users Views   
  username: 'Username'
  password: 'Password' 
  new_password: 'New Password'
  password_confirmation: 'Confirm New Password'
  name: 'Name'
  change: 'Change'
  account: 'Account'
  email_address: 'E-mail Address'
  login: 'Login' 
  edit_user: 'Edit User'
  new_user: 'New User'  
  roles: 'Roles'
  
  personal_preferences: 'Personal Preferences'
  
  login: 'Please Login'
  login_btn: 'Login'
  remember_me: 'Remember me'

  language: 'Language'
  notes: 'Notes'    
  optional: 'Optional'
  required: 'Required'  
  change: 'Change'
  
  new_layout: 'New Layout'    
  edit_layout: 'Edit Layout'
  content_type: 'Content&#8209;Type'    
  remove_layout: 'Remove Layout' 
  delete_layout: 'Delete Layout'
  
  # Page status
  draft: 'Draft'
  reviewed: 'Reviewed'
  hidden: 'Hidden'
  published: 'Published'
  
  new_page: 'New Page'
  edit_page:  'Edit Page'   
  page_title: 'Page Title'  
  remove_tab: 'Remove Tab'  
  add_tab: 'Add Tab'
  status: 'Status'
  page_type: 'Page Type'
  published_at: 'Published at' 
  no_pages: 'No Pages' 
  delete_pages: 'Delete {{pages}}'  
  remove_pages: 'Remove {{pages}}' 
  available_tags_for: 'Available Tags for'
  search_tags: 'Search Tags:'
  add_part: 'Add Part'
  add_child: 'Add Child'
  remove_page: 'Remove Page'
  
  snippets: 'Snippets'          
  snippet: 'Snippet'   
  new_snippet: 'New Snippet'
  edit_snippet: 'Edit Snippet'
  delete_snippet: 'Delete Snippet'
  
  version: 'Version'  
  preferences: 'Preferences' 
  view_site: 'View Site'
  logged_in_as: 'Logged in as'
  log_out: 'Log out'
  
  extensions: 'Extensions' 
  extension: 'Extension'
  website: 'Website'
  version: 'Version'
  
  reference:  'Reference'
  available_tags: 'Available Tags'
  
  # Main Navigation Tags
  content: 'Content'
  design: 'Design'
  settings: 'Settings'
  
  # Sub Navigation Tabs
  pages: 'Pages'
  snippets: 'Snippets'
  layouts: 'Layouts'
  personal: 'Personal'
  users: 'Users'
  extensions: 'Extensions'
  
  # Buttons
  buttons:
    save_and_continue: 'Save and Continue Editing'
    save_changes: 'Save Changes'  
    create: 'Create {{name}}'   
    
  # Select lists
  select:
    none: '<none>' 
    normal: '<normal>'
    inherit: '<inherit>'
    
  # Warning and info text
  text:
    pages: 
      remove_warning: 'Are you sure you want to <strong class="warning">permanently remove</strong> the following {{pages}}?'
    snippets:
      remove_warning: 'Are you sure you want to <strong class="warning">permanently remove</strong> the following snippet?'
    layouts:
      remove_warning: 'Are you sure you want to <strong class="warning">permanently remove</strong> the following layout?'   
  
  # Controllers
  resource_controller:
    saved: "{{humanized_model_name}} saved below."
    validation_errors: "Validation errors occurred while processing this form. Please take a moment to  review the form and correct any input errors before continuing."
    not_found: "{{humanized_model_name}} could not be found."
    removed: "{{humanized_model_name}} has been deleted."
    update_conflict: "{{humanized_model_name}} has been modified since it was last loaded. Changes cannot be saved without potentially losing data." 
  pages_controller:
    saved: "Your page has been saved below."  
    removed_many: "The pages were successfully removed from the site."   
    removed_one: "The page was successfully removed from the site."  
  preferences_controller:
    updated: 'Your preferences have been updated.' 
    error_updating: 'There was an error updating your preferences.'      
  users_controller:
    cannot_delete_self: 'You cannot delete yourself.'    
  welcome_controller:
    logged_out: 'You are now logged out.'  
    invalid_user: 'Invalid username or password.' 
    
  # Active Record Errors
  activerecord:
    errors:
      messages:
        blank: 'required' # required
        taken: 'name already in use' # name_in_use
        not_a_number: 'must be a number' # must be number
        too_short: '{{count}}-character minimum' # character_minimum
        too_long: '{{count}}-character limit' # character_limit
        invalid: 'invalid format' #invalid_format
      models:
        user:
          attributes:
            login:
              taken: 'login already in use' # login already in use
            password:
              confirmation: 'must match confirmation' # password_confirmation
            email:
              invalid: 'invalid e-mail address' # invalid_email
        page:
          attributes:
            slug:
              taken: 'slug already in use for child of parent' # slug_in_use

         
  # Timestamp. This may need to be changed as it will most likely not work for many languages.
  timestamp:
    last_updated: 'Last Updated'
    by: 'by'
    at: 'at'

  date:
    formats:
      default: "%Y-%m-%d"
      short: "%e %b"
      long: "%B %e, %Y"
      only_day: "%e"

    day_names: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
    abbr_day_names: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    month_names: [~, January, February, March, April, May, June, July, August, September, October, November, December]   
    abbr_month_names: [~, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
    order: [ :year, :month, :day ]
  
  time:
    formats:
      timestamp: "%I:%M <small>%p</small> on %B %d, %Y" 
      default: "%a %b %d %H:%M:%S %Z %Y"   
      time: "%H:%M"
      short: "%d %b %H:%M"
      long: "%B %d, %Y %H:%M"
      only_second: "%S"
      
      datetime:
        formats:
          default: "%Y-%m-%dT%H:%M:%S%Z"
          
    am: 'AM'
    pm: 'PM'
 
